development: &default
  adapter: postgresql
  database: leangild_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  username: rkcudjoe
  password:
  host: localhost

test:
  <<: *default
  database: leangild_test
